fix

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -13,9 +13,20 @@ outputs:
 runs:
   using: 'composite'
   steps:
-    - run: ./check_git_repo.sh
+    - run: |
+        # Check if the .git directory exists (indicating the repo has been checked out)
+        if [ ! -d ".git" ]; then
+          echo "::error::Repository has not been checked out. Please ensure 'actions/checkout' is included in the workflow."
+          exit 1
+        fi
       shell: bash
-    - run: ./check_version_category_label.sh
+    - run: |
+        # Check if tags have been retrieved
+        if [ -z "$(git tag)" ]; then
+          echo "::warning::No tags found. Please ensure 'actions/checkout' is run with fetch-depth set to 0 to retrieve all tags."
+        fi
+      shell: bash
+    - run: ${{ github.action_path }}/check_version_category_label.sh
       env:
         PR_NUMBER: ${{ inputs.pr_number }}
       shell: bash
@@ -27,4 +38,4 @@ runs:
       env:
         VERSION_CATEGORY: ${{ steps.version-category.outputs.category }}
         PR_NUMBER: ${{ inputs.pr_number }}
-      run: ./release.sh "$VERSION_CATEGORY"
+      run: ${{ github.action_path }}/release.sh "$VERSION_CATEGORY"
